### ISSUE TITLE
Does Android Nougat support PN65T

### ISSUE THREAD

**Issue by wintonliuwen** [NXPNFCLinux/nxpnfc_android_nougat#1]
We have a product with PN65T on Android Lollipop, we want to upgrate to Android N.
Does Nxp support PN65T on Android Nougat? 
I found libnfc-nci has the definition NXP_EN_PN65T  in  src/nfc/include/nfc_api.h.
But on README.md, it doesn't list PN65T support. 
I want to make sure whether NXP support PN65T on Nougat ?
Thank you.

**Comment by jgeslin** [comment]
Hi,

PN65T is not officially supported on Nougat because it is considered as deprecated since replaced by more recent ICs (PN66T, PN67T, PN80T ...).
The Nougat related delivery from https://github.com/NXPNFCProject may allow running PN65T on Nougat but there is no formal engagement from NXP about it.

Regards,
Jeremy.

**Comment by wintonliuwen** [comment]
Hi Jeremy,

If we want to port PN65T to Nougat based on Lollipop code by ourselves.
Could you give some advice what should we do ?
Thank you.

Best regards,
Winton.Liu

**Comment by wintonliuwen** [comment]
Hi Jeremy,

Comparing the framework API between Android L and Android N, that's the [difference](https://github.com/NXPNFCLinux/nxpnfc_android_marshmallow/blob/master/patch-framework_base_felica.txt):

If we want to use PN65T update from L to N.
1. Framework should use N framework, right ?
https://github.com/NXPNFCProject/NFC_NCIHAL_base
2. Some Android N API doesn't accomplish in Android L, should we also update libnfc-nci to accomplish these API ?

Or any other things should update?

Thanke you!

**Comment by jgeslin** [comment]
I assume you are expecting to use secure element functionality (either UICC or embedded secure element) of PN65T.

I see there 2 options:

1. Simply use the the PN7120 support (PN7120 and PN65T are based on same NFC Controller core) provided as part of https://github.com/NXPNFCLinux/nxpnfc_android_nougat. And update required functionality in the Android.mk files (e.g. "NFC_NXP_ESE:= TRUE") and in the libnfc-nxp.conf file (have a look to the provided [example](https://github.com/NXPNFCProject/NFC_NCIHAL_libnfc-nci/blob/br_android_ncihalx_n/halimpl/pn54x/libnfc-nxp-PN547C2_example.conf)). Give it a try and debug by looking to the NCI communication.

2. Port latest Nougat delivery support from https://github.com/NXPNFCProject, then update the Android.mk files to defined PN65T ("NXP_CHIP_TYPE := $(PN547C2)"). Give it a try and debug by looking to the NCI communication.
