### ISSUE TITLE
node /dev/pn544 is not getting

### ISSUE THREAD

**Issue by bspteam** [NXPNFCLinux/nxpnfc_android_nougat#4]
Hi,
I am trying to port pn7150 in quectel SC20 module (msm8909).
Done all the firmware patches.
My issue has not been sorted out the device node /dev/pn544 is not created yet.

BspDeveloper2@BspDeveloper2:~$ adb shell ls -als /dev/pn544
ls: /dev/pn544: No such file or directory

used insmod command to insert the module pn5xx_i2c.ko in system/lib/modules. but when i use NfcFactoryTestApp it is showing cant connect to pn5xx module.
this is the logcat: https://paste.ubuntu.com/p/ZPRCMcxJvx/
this our schemtic: https://we.tl/t-CZS5hr1o1k 1
device tree:

&i2c_1 { /* BLSP1 QUP1 */
status = “okay”;
nfc:pn544@28 {/*PN7150 NFC*/
	compatible = "qcom,pn544";
	reg = <0x28>;
	pinctrl-names = "nfc_active","nfc_suspend";
    pinctrl-0 = <&nfc_int_active &nfc_disable_active>;
    pinctrl-1 = <&nfc_int_suspend &nfc_disable_suspend>;
    interrupt-parent = <&msm_gpio>;
    interrupts = <14 0x2>;
    interrupt-names = "nfc_irq";
    qcom,nxq-ven = <&msm_gpio 92 0x1>;
    qcom,nxq-irq = <&msm_gpio 14 0x1>;
};

In kernel log it is showing like this
[ 32.308146] pn54x_dev_init
[ 32.329374] init: finit_module for “/system/lib/modules/pn5xx_i2c.ko” failed: File existsinit: write_file: Unable to open ‘/proc/sys/net/ipv6/conf/rmnet0/accept_ra’: No such file or directory
complete kernel log:https://paste.ubuntu.com/p/hXXPwrmrMY/

please support
Regards,
Richu

**Comment by jgeslin** [comment]
If you are creating the kernel module using source from https://github.com/NXPNFCLinux/nxp-pn5xx, the device tree declaration must be similar to https://github.com/NXPNFCLinux/nxp-pn5xx/blob/master/sample_devicetree.txt.
Pay attention to the definitions in the device tree matches the ones in the kernel module (compatible, ven and irq pins, ...)

**Comment by bspteam** [comment]
Hi ,
Thanks for your reply.
these are the gpio pins used in msm8909
NFC_IRQ : gpio14
NFC_EN   : gpio92
SCL: gpio7
SDA:gpio6
used this link for creating kernel:https://github.com/NXPNFCLinux/nxp-pn5xx
this is the device tree : 
```
&i2c_1 { /* BLSP1 QUP1 */
  status = "okay";
	pn544: pn544@28 {/*PN7150 NFC*/
        compatible = "qcom,pn544";
	    reg = <0x28>;
        qcom,nxq-ven = <&msm_gpio 92 0x00>;
        qcom,nxq-irq = <&msm_gpio 14 0x00>;
        interrupt-parent = <&msm_gpio>;
        interrupts = <14 0>;
        interrupt-names = "nfc_irq";
	    pinctrl-names = "nfc_active","nfc_suspend";
        pinctrl-0 = <&nfc_int_active &nfc_disable_active>;
        pinctrl-1 = <&nfc_int_suspend &nfc_disable_suspend>;
       };
};
```
attaching device tree file,adb logcat and kernel log.
please support.

[pn7150.zip](https://github.com/NXPNFCLinux/nxpnfc_android_nougat/files/4190006/pn7150.zip)

Regards,
Richu

**Comment by jgeslin** [comment]
Hi,

I assume you are loading the module manually, thus only trace "pn54x_dev_init" is observed in kernel logs.
The module should be loaded automatically if the device tree declaration is matching the kernel module: I can see that you declared:
`compatible = "qcom,pn544";`
While the kernel module is defined with:
`{ .compatible = "nxp,pn547", },
{ .compatible = "nxp,pn544", }`

Fixing this should allow to have the kernel module loaded at boot, then to see "pn54x_probe" trace in kernel logs. However, you must also match the gpio pins declaration. In you side:
`qcom,nxq-ven and qcom,nxq-irq`
While in kernel driver:
`enable-gpios and interrupt-gpios`

This shall allow you at the end to get the device node "/dev/pn544" visible on your target.

Regards,
Jeremy.

Regards,
Jeremy.

**Comment by bspteam** [comment]
Hi 
Thanks for your reply
changed the device tree accordingly.
```
&i2c_1 { /* BLSP1 QUP1 */
  status = "okay";
	pn544: pn544@28 {/*PN7150 NFC*/
        compatible = "nxp,pn544";
	    reg = <0x28>;
        enable-gpios= <&msm_gpio 92 0x0>;
        interrupt-gpios = <&msm_gpio 14 0x0>;
        interrupt-parent = <&msm_gpio>;
        interrupts = <14 0>;
        interrupt-names = "nfc_irq";
	    pinctrl-names = "nfc_active","nfc_suspend";
        pinctrl-0 = <&nfc_int_active &nfc_disable_active>;
        pinctrl-1 = <&nfc_int_suspend &nfc_disable_suspend>;
       };
};
```
now cold trace more kernel log

```
`msm8909:/ # dmesg|grep pn54
[   27.821516] pn54x_dev_init
[   27.827327] pn54x_probe
[   27.829154] pn544 1-0028: FIRM GPIO <OPTIONAL> error getting from OF node
[   27.835594] pn544 1-0028: CLKREQ GPIO <OPTIONAL> error getting from OF node
[   27.843871] pn54x_get_pdata: could not get nxp,pn54x-pvdd, rc=-19
[   27.849436] pn54x_get_pdata: could not get nxp,pn54x-vbat, rc=-19
[   27.855218] pn54x_get_pdata: could not get nxp,pn54x-pmuvcc, rc=-19
[   27.863034] pn54x_get_pdata: could not get nxp,pn54x-sevdd, rc=-19
[   27.868399] pn54x_probe: request irq_gpio 925
[   27.872552] pn54x_probe: request ven_gpio 1003
[   27.877950] pn54x_probe :not able to get GPIO ven_gpio
[   27.882382] pn544: probe of 1-0028 failed with error -16
`
```
the device node is not yet registered

**Comment by jgeslin** [comment]
Hi,

You have a conflict about gpio pin "&msm_gpio 92" :
```
		camera_snapshot {
			label = "camera_snapshot";
			gpios = <&msm_gpio 92 0x1>;
			linux,input-type = <1>;
			linux,code = <0x2fe>;
			gpio-key,wakeup;
			debounce-interval = <15>;
		};
```
`        enable-gpios= <&msm_gpio 92 0x0>;`

This prevents the kernel module to get the hand on this gpio line.

Regards,
Jeremy.

**Comment by bspteam** [comment]
Hi 
That was the issue.
That you for your support.
